### PR TITLE
Button atom story

### PR DESCRIPTION
**Pull request by wenfeng-xing**

### CODE REVIEW

**Comment by qiqi0725** [comment]
Minor: There's extra margin between text & icon
current: 
image

vs. design: 
image

**Comment by qiqi0725** [comment]
Small discrepancies with design for active state (dark mode)
- primary: remove white border
image
image

- secondary & tertiary: remove background + border, and outline should be a different warning color (#FFBE45 instead of #FF8D00)
image
image

**Comment by wenfeng-xing** [comment]
> 

image
image

@qiqi0725 The space between text and arrow has been modified.

**Comment by qiqi0725** [comment]
One last, secondary hover on active
image


Everything else looks good

**Review by qiqi0725 — APPROVED** [review]

**Comment by wenfeng-xing** [comment]
image
Primary button
image
Secondary button
image
Terniary button

Their styles have been corrected

**Review by Honglin-Lu — APPROVED** [review]

**Pull request merged**
