### PR TITLE
Create release branch on components package publish

### PR DESCRIPTION
**Pull request by iandilling-adaptive**

### CODE REVIEW

**Comment by iandilling-adaptive** [comment]
I updated eslintignore to ignore the files in scripts for now, since they're plain nodejs. The check isn't picking that change up here. Is it safe to bypass?

**Comment by tprince232** [comment]
> I updated eslintignore to ignore the files in scripts for now, since they're plain nodejs. The check isn't picking that change up here. Is it safe to bypass?

Do you think its just this once since the new `.eslintignore` has not been merged yet or will it keep coming up?  I'm fine with bypassing just this once but we should figure out if its fixable to have the `.eslintignore` config reflected in the pipeline going forward.

**Comment by tprince232** [comment]
> > > I updated eslintignore to ignore the files in scripts for now, since they're plain nodejs. The check isn't picking that change up here. Is it safe to bypass?
> > 
> > 
> > Do you think its just this once since the new `.eslintignore` has not been merged yet or will it keep coming up? I'm fine with bypassing just this once but we should figure out if its fixable to have the `.eslintignore` config reflected in the pipeline going forward.
> 
> I think I figured it out. The script in the validator doesn't use the eslintignore file, instead using the .gitignore, but the husky precommit hook does.

Interesting... hopefully the validator can be switched to use the eslintignore file?

**Review by tprince232 — APPROVED** [review]

**Comment by iandilling-adaptive** [comment]
Ok, I ran the scripts locally and confirmed with Wenfeng. It looks like it can be swapped.

**Review by EdAdaptive — APPROVED** [review]

**Pull request merged**
